### ISSUE TITLE
PNML file encoding

### ISSUE THREAD

**Issue by AresEkb** [lip6/pnmlframework#18]
Hi

Does the framework support saving of a PNML file in a specific encoding? For example utf-8?

When I store a pnml file, all non-ascii characters are replaced by question marks.

**Comment by yanntm** [comment]
Hi,
(sorry for the lag)
usually the file encoding is not an issue; the export should use whatever underlying file encoding the file was opened with.
Could you give a minimal example of your problem, in particular the code you use to a) create/open the file b) actually use PNMLFW to export a model
I can't really reproduce the problem as is; in principle there should not be an issue with file encoding all the export uses standard mechanisms.

**Comment by yanntm** [comment]
hmmm, actually maybe there is something to patch on our side, I4ve found a lot of ISO8859 in the code that should be UTF-8, we will release an update 2.2.14 with a patch for this later today.

**Comment by abelgomez** [comment]
Let me "jump" into the discussion.

I didn't see class `PnmlExport` in commit https://github.com/lip6/pnmlframework/commit/345bc52e10012849a2e24fe564b1b507b0f4762e.

There's also a hardcoded reference to ISO-8859 in https://github.com/lip6/pnmlframework/blob/ef6dbabadbc6281dc5dc31120cf0ee8bfa0c1e49/pnmlFw-Utils/src/fr/lip6/move/pnml/framework/general/PnmlExport.java#L383

From a quick inspection, it seems it's dead code (the call to `writeToFileNIOWay` is commented out and the code is marked as experimental), but just for you to know. Maybe you want to do a cleanup, or at least to add a "TODO" comment regarding the new default encoding :)

**Comment by yanntm** [comment]
Thanks @abelgomez I patched the missing ISO occurrence.

So hopefully if you use the latest 2.2.14 that is now available on the update site, you should have UTF-8 @AresEkb 

Please close the issue if this patch solves your problem.

**Comment by yanntm** [comment]
@abelgomez  I'm not sure I understand your last paragraph : we should announce/advertise the switch to UTF-8 ? Or you just wanted me to patch that last occurrence (thanks !) ?
We think UTF-8 is the de facto standard anyway especially for XML; I don't know how we generated this code with ISO encoding in it, but it was probably a mistake no one noticed simply because they only used ascii charset anyway. I hope just hope nobody depended on PNMLFW producing this (ugly) encoding but it seems very unlikely.

**Comment by abelgomez** [comment]
I was only highlighting that, in fact, the code using the ISO-8859 in the `PnmlExport` class seemed to be indeed unreachable dead code, so changing it to UTF8 or keeping it in ISO-8859 didn't have any effect.

But, if it was going to be left in ISO-8859 (since it's dead code, nobody cares) maybe was a good idea to leave a mark saying that now the default is UTF-8 (just in case the dead code goes alive in the future 😄, and then it may be necessary to change it).

**Comment by yanntm** [comment]
ok, then we've done the right thing for our dead (code) then, and needn't fear it troubling us if it "resurrects" :D

**Comment by AresEkb** [comment]
@yanntm Thanks! I've tested, and UTF-8 is supported now!

Here is a related question just for clarification. Should I use the following code to save a model:
```
var exporter = new PnmlExport();
exporter.exportObject(model, fileName, true);
```
Or should I use ResourceSet to save a model?

**Comment by yanntm** [comment]
I think it's two different outputs, the `resourceSet` would be the standard XMI export related to the EMF model, while the `pnmlExport` produces...PNML.
So both XML based formats, but conforming to slightly different grammars.
But it's possible that we hooked up to the appropriate EMF extension points and that the ResoureSet path also produces PNML, I've not checked.
In principle use PnmlExport if you want PNML that might be readable e.g. by another tool.

**Comment by abelgomez** [comment]
Addressing #10 I noticed there's still a reference to ISO-8859 in one of the templates:

https://github.com/lip6/pnmlframework/blob/346b9f9005d5dd4c6fc6f5034caf58c583b21948/pnmlFw-Low_Level_API_Generation/templates-2.2.0/ToPNML/ToPNMLNIO.javajet#L75

This indeed is the template that generates almost all the occurrences manually changed in https://github.com/lip6/pnmlframework/pull/17/commits/345bc52e10012849a2e24fe564b1b507b0f4762e

Nevertheless, calling a code regeneration with the current template does not revert the changes introduced in https://github.com/lip6/pnmlframework/pull/17/commits/345bc52e10012849a2e24fe564b1b507b0f4762e, since the currently generated `toPNML(FileChannel fc)` method does not include the `@generated` annotation that preventing a proper code update.
